apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ${IMAGE_NAME}
  labels:
    cloud.googleapis.com/location: ${CLOUD_RUN_REGION}
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cloudsql-instances: ${PROJECT_ID}:${REGION}:${CLOUD_SQL_INSTANCE}
        run.googleapis.com/container-dependencies: '{"collector":["${IMAGE_NAME}"]}'
        run.googleapis.com/execution-environment: gen2
    spec:
      containers:
      - name: ${IMAGE_NAME}
        image: ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${IMAGE_NAME}:${IMAGE_SHA}
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: ${PROFILE}
${SECRETS_ENV}
        resources:
          limits:
            cpu: "2"
            memory: 1Gi
      - name: collector
        image: us-docker.pkg.dev/cloud-ops-agents-artifacts/cloud-run-gmp-sidecar/cloud-run-gmp-sidecar:1.2.0