# 개발 및 QA 서버 환경(dev)에서 사용
spring:
  datasource:
    username: ${TEST_DB_USER}
    password: ${TEST_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate.format_sql: true
  cloud:
    gcp:
      sql:
        enabled: true
        instance-connection-name: ${TEST_CLOUD_SQL_INSTANCE}
        database-name: ${TEST_DB_NAME}
logging:
  level:
    root: DEBUG
    com.your.package: TRACE