# 로컬 개발 시에 사용
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${LOCAL_DB_NAME}
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  cloud:
    gcp:
      sql:
        enabled: false
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/${LOCAL_DB_NAME}
    user: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PASSWORD}
    locations: classpath:flyway/migration
#    baseline-on-migrate: true
    baseline-version: 1