# 로컬 개발 시에 사용
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${LOCAL_DB_NAME}?serverTimezone=UTC
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  cloud:
    gcp:
      sql:
        enabled: false
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/${LOCAL_DB_NAME}?serverTimezone=UTC
    user: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PASSWORD}
    locations: classpath:flyway/migration
