# 로컬 개발 시에 사용
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${LOCAL_DB_NAME}
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    gcp:
      sql:
        enabled: false