spring:
  application:
    name: backend
  config:
    import:
      - optional:sm://
      - optional:gcp-secretmanager:/
  cloud:
    gcp:
      project-id: continual-lodge-462511-g8
      secretmanager:
        enabled: true

sentry:
  dsn: ${SENTRY_DSN}
  send-default-pii: true
  traces-sample-rate: 1.0
  profiles-sample-rate: 1.0
  environment: production
  debug: false
  exception-resolver-order: 2147483647