server:
  port: ${PORT:8080}
  forward-headers-strategy: framework

spring:
  application:
    name: backend
  config:
    import:
      - optional:file:./.env[.properties]
      - classpath:config/oauth/security.yml
  cloud:
    openfeign:
      client:
        config:
            default:
                connect-timeout: 10000
                read-timeout: 10000
    compatibility-verifier:
      enabled: false
springdoc:
  swagger-ui:
    path: /swagger
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
    disable-swagger-default-url: true