spring:
  config:
    import:
      - optional:classpath:config/postgresql/db-dev.yml

sentry:
  dsn: ${SENTRY_DSN}
  send-default-pii: true
  traces-sample-rate: 1.0
  profiles-sample-rate: 1.0
  environment: development
  debug: false
  exception-resolver-order: 2147483647