# Local profile configuration
# Sentry and monitoring tools are commented out for local development
# sentry:
#   dsn: ${SENTRY_DSN}
#   send-default-pii: true
#   traces-sample-rate: 1.0
#   profiles-sample-rate: 1.0
#   environment: local
#   debug: false
#   exception-resolver-order: 2147483647

spring:
  config:
    import:
      - optional:classpath:config/postgresql/db-local.yml