spring:
  application:
    name: backend
  cloud:
    gcp:
      secretmanager:
        enabled: false
  config:
    import:
      - optional:file:./.env[.properties]
      - classpath:config/oauth/security.yml
springdoc:
  swagger-ui:
    with-credentials: true
    path: /swagger
