server:
  forward-headers-strategy: framework

spring:
  application:
    name: backend
  config:
    import:
      - optional:file:./.env[.properties]
      - classpath:config/oauth/security.yml
springdoc:
  swagger-ui:
    path: /swagger
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
    disable-swagger-default-url: true