spring:
  application:
    name: backend
  cloud:
    gcp:
      secretmanager:
        enabled: false
  config:
    import:
      - optional:file:./.env[.properties]

springdoc:
  swagger-ui:
    with-credentials: true
    path: /swagger

test:
  value: ${TEST_VALUE}