CREATE TABLE trip_group
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    group_name VARCHAR(255),
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_trip_group PRIMARY KEY (id)
);

ALTER TABLE trip_group
    ADD CONSTRAINT FK_TRIP_GROUP_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES users (id);

ALTER TABLE trip_group
    ADD CONSTRAINT FK_TRIP_GROUP_ON_UPDATED_BY FOREIGN KEY (updated_by) REFERENCES users (id);