CREATE TABLE comparison_table
(
    table_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    table_name VARCHAR(255),
    trip_group BIGINT,
    created_by BIGINT,
    factors    JSONB,
    CONSTRAINT pk_comparison_table PRIMARY KEY (table_id)
);

ALTER TABLE comparison_table
    ADD CONSTRAINT FK_COMPARISON_TABLE_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES users (id);

ALTER TABLE comparison_table
    ADD CONSTRAINT FK_COMPARISON_TABLE_ON_TRIP_GROUP FOREIGN KEY (trip_group) REFERENCES trip_group (id);