CREATE TABLE comparison_table
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    table_name VARCHAR(255),
    trip_board BIGINT,
    created_by BIGINT,
    factors    JSONB,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_comparison_table PRIMARY KEY (id)
);

ALTER TABLE comparison_table
    ADD CONSTRAINT FK_COMPARISON_TABLE_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES users (id);

ALTER TABLE comparison_table
    ADD CONSTRAINT FK_COMPARISON_TABLE_ON_TRIP_BOARD FOREIGN KEY (trip_board) REFERENCES trip_board (id);