CREATE TABLE comparison_accommodation
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    comparison_table_id BIGINT                                  NOT NULL,
    accommodation_id    BIGINT                                  NOT NULL,
    position            INTEGER                                 NOT NULL,
    CONSTRAINT pk_comparison_accommodation PRIMARY KEY (id)
);

ALTER TABLE comparison_accommodation
    ADD CONSTRAINT uq_cmp_accom UNIQUE (accommodation_id);

ALTER TABLE comparison_accommodation
    ADD CONSTRAINT FK_COMPARISON_ACCOMMODATION_ON_ACCOMMODATION FOREIGN KEY (accommodation_id) REFERENCES accommodation (id);

ALTER TABLE comparison_accommodation
    ADD CONSTRAINT FK_COMPARISON_ACCOMMODATION_ON_COMPARISON_TABLE FOREIGN KEY (comparison_table_id) REFERENCES comparison_table (table_id);