CREATE TABLE user_trip_board (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    trip_board_id BIGINT NOT NULL,
    invitation_url VARCHAR(255) UNIQUE NOT NULL,
    invitation_active BOOLEAN NOT NULL DEFAULT TRUE,
    role VARCHAR(20) NOT NULL DEFAULT 'MEMBER',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_user_trip_board_user 
        FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_user_trip_board_trip_board 
        FOREIGN KEY (trip_board_id) REFERENCES trip_board(id),
    CONSTRAINT uk_user_trip_board_user_board 
        UNIQUE (user_id, trip_board_id)
);

CREATE INDEX idx_user_trip_board_invitation_url ON user_trip_board(invitation_url);
CREATE INDEX idx_user_trip_board_user_id ON user_trip_board(user_id);
CREATE INDEX idx_user_trip_board_trip_board_id ON user_trip_board(trip_board_id);